### ISSUE TITLE
`performance-table` fails: `chance_agreement` cannot get `data["all"]["ground_truths"]`

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/morphoclass#64]
When running the following:

```bash
cd dvc/
find training/ -iname "*chk" | xargs morphoclass -vv performance-table --output-dir ../notebooks/results-performance-table
```

The following error is produced:

```text
15:04:29 morphoclass.console.main (I) Running them morphoclass entrypoint
15:04:29 morphoclass.console.cmd_performance_table (I) Got 409 checkpoints
15:04:29 morphoclass.console.cmd_performance_table (I) Loading libraries
15:04:32 morphoclass.console.cmd_performance_table (I) Creating the performance summary table
15:04:33 morphoclass.console.performance_table (I) Found 409 checkpoint files
15:04:33 morphoclass.console.performance_table (I) Processing checkpoint 1 of 409: '/workdir/dvc/training/checkpoints-lida-alt-neurites/in-merged-all-decision-tree-deepwalk-stratified-k-fold/checkpoint.chk'
15:04:34 morphoclass.console.performance_table (I) Processing checkpoint 2 of 409: '/workdir/dvc/training/checkpoints-lida-alt-neurites/janelia-L5-basal-perslay-tmd-stratified-k-fold/checkpoint.chk'
Traceback (most recent call last):
  File "/home/casalegn/.local/bin/morphoclass", line 33, in <module>
    sys.exit(load_entry_point('morphoclass', 'console_scripts', 'morphoclass')())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/workdir/src/morphoclass/console/cmd_performance_table.py", line 64, in cli
    make_performance_table(checkpoint_paths, output_dir)
  File "/workdir/src/morphoclass/console/performance_table.py", line 76, in make_performance_table
    table_rows.append(make_report_row(data))
  File "/workdir/src/morphoclass/console/performance_table.py", line 176, in make_report_row
    chance_agreement_score = chance_agreement(data["all"]["ground_truths"])
KeyError: 'ground_truths'
```

**Comment by FrancescoCasalegno** [comment]
## Debugging

This bug is caused by the fact that `train_dm_models` ( = training of neural nets models: GNN, CNN, PersLay) does not write `data["all"]["ground_truths"]`
https://github.com/BlueBrain/morphoclass/blob/5eb63eb08e772a0b8a0efc34cc4c50d55caf1b87/src/morphoclass/training/cli.py#L345

This is unlike what happens with `train_ml_models`, which does write `data["all"]["ground_truths"]`
https://github.com/BlueBrain/morphoclass/blob/5eb63eb08e772a0b8a0efc34cc4c50d55caf1b87/src/morphoclass/training/cli.py#L293

---

## Proposed solution

We can compute `chance_agreement` on the concatenation of the `"ground_truths"` of each split in `data["splits"]`.
